// ─── Goal Hierarchy ───────────────────────────────────────────────────────────

/**
 * A complete set of financial targets for a single scope (global, year, or month).
 */
export interface GoalProfile {
  dailyGoal: number;
  weeklyGoal: number;
  annualCost: number;
}

/**
 * Cost-based survival targets derived from the actual day span of expense data.
 * These are never persisted — always computed on the fly using:
 *   dailyCost = totalExpenses / daySpan  (earliest→latest expense, inclusive)
 * All other targets are simple multiples of dailyCost.
 */
export interface CostBasedTarget {
  /** dailyCost × 7 — minimum weekly revenue to cover operating costs. */
  weeklySurvival: number;
  /** dailyCost — minimum daily revenue to cover operating costs. */
  dailySurvival: number;
  /** dailyCost × 30 — minimum monthly revenue to cover operating costs. */
  monthlySurvival: number;
  /** dailyCost × 365 — projected annual operating cost. */
  annualCost: number;
}

// ─── Persisted Data ──────────────────────────────────────────────────────────

export interface TableRow {
  id: string;
  date: string;        // "YYYY-MM-DD"
  /**
   * Meaning depends on entryType:
   *   'revenue'  → R$ earned (0 = rest day, skipped in averages)
   *   'deposit'  → R$ invested
   *   'waiver'   → days justified (waiverMode='days') or direct R$ credit (waiverMode='value')
   *   'expense'  → dynamic cost entry; value = monthlyValue × monthCount
   */
  value: number;
  description?: string;
  /**
   *   'revenue'  — operational income (default for legacy rows)
   *   'deposit'  — investment / aporte
   *   'waiver'   — excused downtime period or direct monetary justification.
   *                date = start of the period; description = reason
   *   'expense'  — dynamic cost (e.g. insurance, IPVA, financing);
   *                value = monthlyValue × monthCount (auto-computed on creation)
   *   'partner_in'  — partnership credit / reimbursement. Isolated from grossTotal;
   *                    adds to totalPartnerIn and globalGoalBalance.
   *   'partner_out' — partnership debit / charge. Isolated from totalExpenses;
   *                    adds to totalPartnerOut and subtracts from globalGoalBalance.
   * Omitted on legacy rows — treated as 'revenue' for full backward compatibility.
   */
  entryType?: 'revenue' | 'deposit' | 'waiver' | 'expense' | 'partner_in' | 'partner_out';
  /**
   * For 'expense' entries only — the monthly cost amount (R$).
   * Used to reconstruct the total: value = monthlyValue × monthCount.
   */
  monthlyValue?: number;
  /**
   * For 'expense' entries only — how many months this cost spans.
   * Used to reconstruct the total: value = monthlyValue × monthCount.
   */
  monthCount?: number;
  /**
   * Optional period start date for 'revenue' (and 'expense') entries.
   * When set alongside periodEnd, the metrics engine distributes row.value
   * across every calendar day in [periodStart, periodEnd] so that lump-sum
   * payments don't inflate daily/weekly/monthly averages.
   * For single-day entries leave undefined.
   */
  periodStart?: string; // "YYYY-MM-DD"
  /**
   * Optional period end date — must be set together with periodStart.
   * row.date is set to periodStart on creation for backward‑compat.
   */
  periodEnd?: string;   // "YYYY-MM-DD"
  /**
   * When present, marks this row as auto-generated by the prediction engine.
   *   'predicted' — synthetic average-based projection row
   *   'cloned'    — exact copy of a historical row mapped to a future date
   * Enables visual distinction, bulk deletion, and filtering.
   */
  generatedBy?: 'predicted' | 'cloned';
  /**
   * Audit trail for cloned rows — the source YYYY-MM from which
   * this entry was copied. E.g. "2025-12".
   */
  clonedFrom?: string;
  category?: string;
  tags?: string;
  metadataJson?: string;
}

export interface TableGoals {
  // ── Legacy flat records (kept for backward compat with calculateStrictGlobalBalance) ──
  /**
   * Per-calendar-year daily revenue target (e.g. { 2026: 86.00 }).
   * Year-keyed so changing the 2027 target never overwrites 2026 history.
   */
  dailyGoals: Record<number, number>;
  /**
   * Per-calendar-year weekly revenue target (e.g. { 2026: 600.00 }).
   * Used by calculateStrictGlobalBalance to score each historical week
   * against the goal that was in effect for THAT specific year.
   */
  weeklyGoals: Record<string | number, number>;
  /**
   * Per-calendar-year vehicle/operating cost target.
   * Key = full year number (e.g. 2026), value = cost in BRL.
   */
  annualCosts: Record<number, number>;

  // ── New hierarchical goal system (additive — never replaces legacy records) ──
  /**
   * The ultimate fallback. Applied whenever no yearly or monthly override exists.
   */
  globalGoals?: GoalProfile;
  /**
   * Per-year overrides. Key = year number (can be any year, past or future).
   * Overrides globalGoals for that specific year.
   */
  yearlyGoals?: Record<number, GoalProfile>;
  /**
   * Per-month overrides. Key = "YYYY-MM".
   * Overrides both yearlyGoals and globalGoals for that specific month.
   */
  monthlyGoals?: Record<string, GoalProfile>;
}

export interface CoinTable {
  id: string;
  name: string;
  description?: string;
  createdAt: string;   // ISO timestamp
  updatedAt: string;   // ISO timestamp
  rows: TableRow[];
  goals: TableGoals;
  isDeleted?: boolean;
  activeSectors?: string[];
}

export type DB = {
  tables: CoinTable[];
  aiCostCurrentMonth?: number;
  aiCostLastReset?: string;
};

// ─── Computed Metrics (never persisted, always derived) ───────────────────────

export interface MonthMetrics {
  grossMonthly: number;
  dailyAvg: number;
  weeklyAvg: number;
  lastWeekGross: number;
  dailyPayments: Record<string, number>; // "YYYY-MM-DD" → value
  investment?: number;
  expense?: number;
}

export interface YearMetrics {
  grossAnnual: number;
  /** Year-scoped expenses: sum of expense values prorated to this year.
   *  Point-in-time: full value. Multi-year: dailyRate × overlapDays. */
  yearExpenses: number;
  dailyAvg: number;
  /** grossAnnual / number of active weeks in this year */
  weeklyAvg: number;
  /** grossAnnual / number of active months in this year */
  monthlyAvg: number;
}

export interface TableMetrics {
  grossTotal: number;
  globalDailyAvg: number;
  globalWeeklyAvg: number;
  globalMonthlyAvg: number;
  globalAnnualAvg: number;
  globalGoalBalance: number;
  totalElapsedWeeks: number;
  waivedWeeks: number;
  billableWeeks: number;
  totalWaiverCredit: number;
  timeBankBalance: number;
  byYear: Record<string, YearMetrics>;
  byMonth: Record<string, MonthMetrics>;
  byWeek: Record<string, number>;
  totalExpenses: number;
  annualExpenses: number;
  netBalance: number;

  // ─── Survival / Break-Even Goals ──────────
  survivalDaily: number;
  survivalWeekly: number;
  survivalMonthly: number;
  survivalAnnualCost: number;

  // ─── Investment / Deposit Metrics ────────
  depositCount: number;
  totalInvested: number;
  totalInterestEarned: number;
  investmentBalance: number;
  globalTotalDeposited: number;
  globalTotalYield: number;
  globalBalance: number;
  portfolioTimeline: Array<{
    month: string;
    monthlyDeposit: number;
    currentMonthYield: number;
    accumulatedPrincipal: number;
    accumulatedYield: number;
    totalBalance: number;
  }>;

  // ─── Advanced Statistics ──
  maxTransaction: number;
  minTransaction: number;
  medianTransaction: number;
  modeTransaction: number;
  stdDeviation: number;

  // ─── Partnership Ledger ─────────────────
  totalPartnerIn: number;
  totalPartnerOut: number;

  // ─── Combined Metrics ──────────────────────────
  grossWithPartner: number;
  expensesWithPartner: number;
  netWithPartner: number;

  // ─── Historically-Accumulated Week Equivalents ─────────────────
  grossTotalWeeks: number;
  waiverTotalWeeks: number;
  goalTotalWeeks: number;
  netBalanceWeeks: number;
}

// ─── Projection Engine ────────────────────────────────────────────────────────

export interface ProjectionPoint {
  month: number;
  totalDeposited: number;
  accumulatedInterest: number;
  totalBalance: number;
  monthlyYield: number;
}

// ─── UI State ─────────────────────────────────────────────────────────────────

export type ModalMode = 'create' | 'edit' | null;
